### ISSUE TITLE
Installation working, but uploading images doesn't

### ISSUE THREAD

**Issue by jmuheim** [SammyLin/redactor-rails#46] opened 2013-02-11 14:07 UTC
When clicking on the "upload image" link, I get errors like the following:

![Google ChromeScreenSnapz001](https://f.cloud.github.com/assets/1814983/145163/4d29189c-7454-11e2-801d-3e3592b99422.png)

How should I try to debug this? Thanks.

**Comment by daao87** [comment] 2015-02-04 11:30
I had the 500 server error. Try installing MiniMagick on your system. In Ubuntu:

`sudo apt-get install imagemagick`

**Comment by wilgoszpl** [comment] 2015-02-08 22:52
@jmuheim @daao87 @regdog @jhanggi 

Currently I couldn't reproduce this error. I close this issue. If I'm wrong and this bug isn't solved yet, please, notify me or open another issue.

It would be great if you could add some detailed description how to reproduce that. Thanks!

**Closed by wilgoszpl** 2015-02-08 22:52 UTC
